version: '3'
services:
  redis:
    image: "redis:latest"
    networks:
      - my-custom-network
    volumes:
      - redis-data:/data

  go-short-url:
    build: .
    ports:
      - "8080:8080"
    networks:
      - my-custom-network

networks:
  my-custom-network:
    driver: bridge

volumes:
  redis-data:
